### ISSUE TITLE
Improve element visual separation in the theme

### ISSUE THREAD

**Issue by HumbeBee** [Ebyrdeu/gruvbox-material-dark#1]
Thanks for this awesome theme! Just noticed one small usability concern:

Elements are hard to distinguish without clear visual separation:
![image](https://github.com/user-attachments/assets/28aa9b35-f3e1-4cc6-b9f8-111ef433c0c6)

For comparison, here's how it looks in another theme:
![image](https://github.com/user-attachments/assets/ed772ff3-2398-45a9-b28e-b2980403668b)

This is just an example for illustration. Feel free to implement any solution that best fits the theme's design philosophy.

Thank you for considering this feedback!

**Comment by Ebyrdeu** [comment]
Hi, @HumbeBee. Based on your screenshot, it looks like you’re aiming for either a contrasting version of the theme or simply different colors for the borders on the sidebars.

IntelliJ is quite limited when it comes to theming, and it’s challenging to theme each component effectively. Most contrast themes are implemented by globally changing the background color to something different from the color scheme's background. In my opinion, this often results in awkward contrasts. Unless I can find a good way to implement changes specifically for the sidebars without altering the global background, I won’t be creating a contrasting version of the theme in the near future.

But for now, I’ve added border colors for the sidebars, which might help with clarity.
Previously, each theme had borders set to bg0.
Now, the borders are set to bg1, which I hope will be enough to distinguish the sidebars.


You can either wait until IntelliJ approves the new plugin version (usually it takes about two days, more or less) or build it yourself from the sources.
